on:
  workflow_dispatch:
    inputs:
      application:
        description: The name of the application to be deployed.
        type: string
        required: true
      image:
        description: The image being deployed.
        type: string
        required: true
      tag:
        description: The image tag being deployed.
        type: string
        required: true

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r scripts/requirements.txt
      - run: ./scripts/patch_application.py "$APPLICATION" "$IMAGE" "$TAG"
        env:
          APPLICATION: ${{ inputs.application }}
          IMAGE: ${{ inputs.image }}
          TAG: ${{ inputs.tag }}
      - run: git diff
      # TODO commit
